################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
C++M_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CC_DEPS := 
C++_DEPS := 
CCM_DEPS := 
EXECUTABLES := 
OBJS := 
C_UPPER_DEPS := 
CXX_DEPS := 
CXXM_DEPS := 
C++M_DEPS := 
C_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
autogen \
simplicity_sdk_2025.6.2/hardware/board/src \
simplicity_sdk_2025.6.2/hardware/driver/configuration_over_swo/src \
simplicity_sdk_2025.6.2/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_eusart \
simplicity_sdk_2025.6.2/platform/Device/SiliconLabs/EFR32MG24/Source \
simplicity_sdk_2025.6.2/platform/bootloader/api \
simplicity_sdk_2025.6.2/platform/bootloader/app_properties \
simplicity_sdk_2025.6.2/platform/bootloader/core/flash \
simplicity_sdk_2025.6.2/platform/common/src \
simplicity_sdk_2025.6.2/platform/driver/debug/src \
simplicity_sdk_2025.6.2/platform/driver/gpio/src \
simplicity_sdk_2025.6.2/platform/driver/leddrv/src \
simplicity_sdk_2025.6.2/platform/emdrv/dmadrv/src \
simplicity_sdk_2025.6.2/platform/emdrv/nvm3/src \
simplicity_sdk_2025.6.2/platform/emlib/src \
simplicity_sdk_2025.6.2/platform/peripheral/src \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/pa-conversions \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/rail_util_pti \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/rail_util_rssi \
simplicity_sdk_2025.6.2/platform/radio/rail_lib/plugin/rail_util_sequencer \
simplicity_sdk_2025.6.2/platform/security/sl_component/se_manager/src \
simplicity_sdk_2025.6.2/platform/security/sl_component/sl_mbedtls_support/src \
simplicity_sdk_2025.6.2/platform/security/sl_component/sl_protocol_crypto/src \
simplicity_sdk_2025.6.2/platform/security/sl_component/sl_psa_driver/src \
simplicity_sdk_2025.6.2/platform/service/clock_manager/src \
simplicity_sdk_2025.6.2/platform/service/device_init/src \
simplicity_sdk_2025.6.2/platform/service/device_manager/clocks \
simplicity_sdk_2025.6.2/platform/service/device_manager/devices \
simplicity_sdk_2025.6.2/platform/service/device_manager/src \
simplicity_sdk_2025.6.2/platform/service/interrupt_manager/src \
simplicity_sdk_2025.6.2/platform/service/iostream/src \
simplicity_sdk_2025.6.2/platform/service/legacy_hal/src \
simplicity_sdk_2025.6.2/platform/service/memory_manager/src \
simplicity_sdk_2025.6.2/platform/service/mpu/src \
simplicity_sdk_2025.6.2/platform/service/sl_main/src \
simplicity_sdk_2025.6.2/platform/service/sleeptimer/src \
simplicity_sdk_2025.6.2/platform/service/udelay/src \
simplicity_sdk_2025.6.2/protocol/openthread/platform-abstraction/efr32 \
simplicity_sdk_2025.6.2/protocol/openthread/src/legacy_hal \
simplicity_sdk_2025.6.2/util/plugin/security_manager \
simplicity_sdk_2025.6.2/util/silicon_labs/silabs_core/queue \
simplicity_sdk_2025.6.2/util/third_party/mbedtls/library \
simplicity_sdk_2025.6.2/util/third_party/openthread/examples/apps/cli \
simplicity_sdk_2025.6.2/util/third_party/openthread/examples/platforms/utils \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/cli \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/api \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/backbone_router \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/border_router \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/coap \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/common \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/crypto \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/diags \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/instance \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/mac \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/meshcop \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/net \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/radio \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/thread \
simplicity_sdk_2025.6.2/util/third_party/openthread/src/core/utils \
simplicity_sdk_2025.6.2/util/third_party/openthread/third_party/tcplp/bsdtcp/cc \
simplicity_sdk_2025.6.2/util/third_party/openthread/third_party/tcplp/bsdtcp \
simplicity_sdk_2025.6.2/util/third_party/openthread/third_party/tcplp/lib \

