#!/usr/bin/env python3
"""
PreToolUse Hook Guard: Protects Silicon Labs autogenerated files and SDK internals
from accidental AI modification.
"""
import sys
import json
import os

FORBIDDEN_PATTERNS = [
    "autogen/",
    "autogen\\",
    "simplicity_sdk_",
    ".slps",
    ".projectlinkstore",
    ".silabsExtContext",
]

def main():
    try:
        raw_input = sys.stdin.read()
        if not raw_input:
            print(json.dumps({"decision": "allow"}))
            return

        payload = json.loads(raw_input)
        tool_call = payload.get("toolCall", {})
        tool_name = tool_call.get("name", "")
        tool_args = tool_call.get("args", {})

        # Check target file arguments across various edit tools
        target_file = (
            tool_args.get("TargetFile")
            or tool_args.get("AbsolutePath")
            or tool_args.get("FilePath")
            or ""
        )

        target_file_normalized = target_file.replace("\\", "/").lower()

        for pattern in FORBIDDEN_PATTERNS:
            pattern_norm = pattern.replace("\\", "/").lower()
            if pattern_norm in target_file_normalized:
                response = {
                    "decision": "deny",
                    "reason": (
                        f"Modification of autogenerated / SDK protected path '{pattern}' is strictly FORBIDDEN. "
                        "Silicon Labs autogen files are generated by Simplicity Studio / SLC. "
                        "Please modify application code in 'src/' or configure components via '.slcp' instead."
                    ),
                }
                print(json.dumps(response))
                return

        print(json.dumps({"decision": "allow"}))
    except Exception as e:
        # Fallback to allow on unexpected error so agent isn't blocked, but log reason
        print(json.dumps({"decision": "allow", "reason": f"Hook exception: {str(e)}"}))

if __name__ == "__main__":
    main()
