# guard_autogen.ps1 - PreToolUse Hook Guard for Windows PowerShell
# Protects Silicon Labs autogenerated files and SDK internals from accidental AI modification.

$inputJson = [Console]::In.ReadToEnd()
if ([string]::IsNullOrWhiteSpace($inputJson)) {
    Write-Output '{"decision": "allow"}'
    exit 0
}

try {
    $payload = $inputJson | ConvertFrom-Json
    $toolCall = $payload.toolCall
    $toolArgs = $toolCall.args

    $targetFile = ""
    if ($toolArgs.TargetFile) { $targetFile = $toolArgs.TargetFile }
    elseif ($toolArgs.AbsolutePath) { $targetFile = $toolArgs.AbsolutePath }
    elseif ($toolArgs.FilePath) { $targetFile = $toolArgs.FilePath }

    $targetNorm = $targetFile.Replace('\', '/').ToLower()
    $forbidden = @("autogen/", "simplicity_sdk_", ".slps", ".projectlinkstore", ".silabsextcontext")

    foreach ($pattern in $forbidden) {
        if ($targetNorm.Contains($pattern)) {
            $reason = "Modification of autogenerated / SDK protected path '$pattern' is strictly FORBIDDEN. Silicon Labs autogen files are generated by Simplicity Studio / SLC. Please modify application code in 'src/' or configure components via '.slcp' instead."
            $res = [PSCustomObject]@{
                decision = "deny"
                reason = $reason
            }
            Write-Output ($res | ConvertTo-Json -Compress)
            exit 0
        }
    }

    Write-Output '{"decision": "allow"}'
}
catch {
    Write-Output '{"decision": "allow"}'
}
